export const getAllUsersMockData = [
    {
        "login": "mojombo",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mojombo",
        "html_url": "https://github.com/mojombo",
        "followers_url": "https://api.github.com/users/mojombo/followers",
        "following_url": "https://api.github.com/users/mojombo/following{/other_user}",
        "gists_url": "https://api.github.com/users/mojombo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mojombo/subscriptions",
        "organizations_url": "https://api.github.com/users/mojombo/orgs",
        "repos_url": "https://api.github.com/users/mojombo/repos",
        "events_url": "https://api.github.com/users/mojombo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mojombo/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
    },
    {
        "login": "defunkt",
        "id": 2,
        "node_id": "MDQ6VXNlcjI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/defunkt",
        "html_url": "https://github.com/defunkt",
        "followers_url": "https://api.github.com/users/defunkt/followers",
        "following_url": "https://api.github.com/users/defunkt/following{/other_user}",
        "gists_url": "https://api.github.com/users/defunkt/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/defunkt/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/defunkt/subscriptions",
        "organizations_url": "https://api.github.com/users/defunkt/orgs",
        "repos_url": "https://api.github.com/users/defunkt/repos",
        "events_url": "https://api.github.com/users/defunkt/events{/privacy}",
        "received_events_url": "https://api.github.com/users/defunkt/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
    },
]

export const getUserByTermMockData = {
    "total_count": 253761,
    "incomplete_results": false,
    "items": [
        {
            "login": "jose",
            "id": 763676,
            "node_id": "MDQ6VXNlcjc2MzY3Ng==",
            "avatar_url": "https://avatars.githubusercontent.com/u/763676?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jose",
            "html_url": "https://github.com/jose",
            "followers_url": "https://api.github.com/users/jose/followers",
            "following_url": "https://api.github.com/users/jose/following{/other_user}",
            "gists_url": "https://api.github.com/users/jose/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jose/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jose/subscriptions",
            "organizations_url": "https://api.github.com/users/jose/orgs",
            "repos_url": "https://api.github.com/users/jose/repos",
            "events_url": "https://api.github.com/users/jose/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jose/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false,
            "score": 1
        },
        {
            "login": "0joseDark",
            "id": 162716366,
            "node_id": "U_kgDOCbLazg",
            "avatar_url": "https://avatars.githubusercontent.com/u/162716366?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/0joseDark",
            "html_url": "https://github.com/0joseDark",
            "followers_url": "https://api.github.com/users/0joseDark/followers",
            "following_url": "https://api.github.com/users/0joseDark/following{/other_user}",
            "gists_url": "https://api.github.com/users/0joseDark/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/0joseDark/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/0joseDark/subscriptions",
            "organizations_url": "https://api.github.com/users/0joseDark/orgs",
            "repos_url": "https://api.github.com/users/0joseDark/repos",
            "events_url": "https://api.github.com/users/0joseDark/events{/privacy}",
            "received_events_url": "https://api.github.com/users/0joseDark/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false,
            "score": 1
        },
    ]
}

export const getByUserMockData = {
    "login": "joseguti99",
    "id": 88012457,
    "node_id": "MDQ6VXNlcjg4MDEyNDU3",
    "avatar_url": "https://avatars.githubusercontent.com/u/88012457?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/joseguti99",
    "html_url": "https://github.com/joseguti99",
    "followers_url": "https://api.github.com/users/joseguti99/followers",
    "following_url": "https://api.github.com/users/joseguti99/following{/other_user}",
    "gists_url": "https://api.github.com/users/joseguti99/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/joseguti99/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/joseguti99/subscriptions",
    "organizations_url": "https://api.github.com/users/joseguti99/orgs",
    "repos_url": "https://api.github.com/users/joseguti99/repos",
    "events_url": "https://api.github.com/users/joseguti99/events{/privacy}",
    "received_events_url": "https://api.github.com/users/joseguti99/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false,
    "name": "José Gutierrez",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 11,
    "public_gists": 0,
    "followers": 1,
    "following": 0,
    "created_at": "2021-07-27T01:33:31Z",
    "updated_at": "2025-06-02T22:16:21Z"
}

export const getReposByUsernameMockData = [
    {
        "id": 4061,
        "node_id": "MDEwOlJlcG9zaXRvcnk0MDYx",
        "name": "auto_migrations",
        "full_name": "pjhyett/auto_migrations",
        "private": false,
        "owner": {
            "login": "pjhyett",
            "id": 3,
            "node_id": "MDQ6VXNlcjM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pjhyett",
            "html_url": "https://github.com/pjhyett",
            "followers_url": "https://api.github.com/users/pjhyett/followers",
            "following_url": "https://api.github.com/users/pjhyett/following{/other_user}",
            "gists_url": "https://api.github.com/users/pjhyett/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pjhyett/subscriptions",
            "organizations_url": "https://api.github.com/users/pjhyett/orgs",
            "repos_url": "https://api.github.com/users/pjhyett/repos",
            "events_url": "https://api.github.com/users/pjhyett/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pjhyett/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/pjhyett/auto_migrations",
        "description": "Rails plugin for automating migrations",
        "fork": false,
        "url": "https://api.github.com/repos/pjhyett/auto_migrations",
        "forks_url": "https://api.github.com/repos/pjhyett/auto_migrations/forks",
        "keys_url": "https://api.github.com/repos/pjhyett/auto_migrations/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/pjhyett/auto_migrations/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/pjhyett/auto_migrations/teams",
        "hooks_url": "https://api.github.com/repos/pjhyett/auto_migrations/hooks",
        "issue_events_url": "https://api.github.com/repos/pjhyett/auto_migrations/issues/events{/number}",
        "events_url": "https://api.github.com/repos/pjhyett/auto_migrations/events",
        "assignees_url": "https://api.github.com/repos/pjhyett/auto_migrations/assignees{/user}",
        "branches_url": "https://api.github.com/repos/pjhyett/auto_migrations/branches{/branch}",
        "tags_url": "https://api.github.com/repos/pjhyett/auto_migrations/tags",
        "blobs_url": "https://api.github.com/repos/pjhyett/auto_migrations/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/pjhyett/auto_migrations/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/pjhyett/auto_migrations/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/pjhyett/auto_migrations/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/pjhyett/auto_migrations/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/pjhyett/auto_migrations/languages",
        "stargazers_url": "https://api.github.com/repos/pjhyett/auto_migrations/stargazers",
        "contributors_url": "https://api.github.com/repos/pjhyett/auto_migrations/contributors",
        "subscribers_url": "https://api.github.com/repos/pjhyett/auto_migrations/subscribers",
        "subscription_url": "https://api.github.com/repos/pjhyett/auto_migrations/subscription",
        "commits_url": "https://api.github.com/repos/pjhyett/auto_migrations/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/pjhyett/auto_migrations/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/pjhyett/auto_migrations/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/pjhyett/auto_migrations/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/pjhyett/auto_migrations/contents/{+path}",
        "compare_url": "https://api.github.com/repos/pjhyett/auto_migrations/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/pjhyett/auto_migrations/merges",
        "archive_url": "https://api.github.com/repos/pjhyett/auto_migrations/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/pjhyett/auto_migrations/downloads",
        "issues_url": "https://api.github.com/repos/pjhyett/auto_migrations/issues{/number}",
        "pulls_url": "https://api.github.com/repos/pjhyett/auto_migrations/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/pjhyett/auto_migrations/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/pjhyett/auto_migrations/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/pjhyett/auto_migrations/labels{/name}",
        "releases_url": "https://api.github.com/repos/pjhyett/auto_migrations/releases{/id}",
        "deployments_url": "https://api.github.com/repos/pjhyett/auto_migrations/deployments",
        "created_at": "2008-03-16T00:44:24Z",
        "updated_at": "2024-09-21T18:21:52Z",
        "pushed_at": "2013-04-25T20:41:57Z",
        "git_url": "git://github.com/pjhyett/auto_migrations.git",
        "ssh_url": "git@github.com:pjhyett/auto_migrations.git",
        "clone_url": "https://github.com/pjhyett/auto_migrations.git",
        "svn_url": "https://github.com/pjhyett/auto_migrations",
        "homepage": "http://errtheblog.com/posts/65-automatically",
        "size": 118,
        "stargazers_count": 146,
        "watchers_count": 146,
        "language": "Ruby",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 37,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 37,
        "open_issues": 2,
        "watchers": 146,
        "default_branch": "master"
    },
    {
        "id": 112071,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMTIwNzE=",
        "name": "blackjax",
        "full_name": "pjhyett/blackjax",
        "private": false,
        "owner": {
            "login": "pjhyett",
            "id": 3,
            "node_id": "MDQ6VXNlcjM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pjhyett",
            "html_url": "https://github.com/pjhyett",
            "followers_url": "https://api.github.com/users/pjhyett/followers",
            "following_url": "https://api.github.com/users/pjhyett/following{/other_user}",
            "gists_url": "https://api.github.com/users/pjhyett/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pjhyett/subscriptions",
            "organizations_url": "https://api.github.com/users/pjhyett/orgs",
            "repos_url": "https://api.github.com/users/pjhyett/repos",
            "events_url": "https://api.github.com/users/pjhyett/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pjhyett/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/pjhyett/blackjax",
        "description": "buzzword-powered blackjack game",
        "fork": false,
        "url": "https://api.github.com/repos/pjhyett/blackjax",
        "forks_url": "https://api.github.com/repos/pjhyett/blackjax/forks",
        "keys_url": "https://api.github.com/repos/pjhyett/blackjax/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/pjhyett/blackjax/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/pjhyett/blackjax/teams",
        "hooks_url": "https://api.github.com/repos/pjhyett/blackjax/hooks",
        "issue_events_url": "https://api.github.com/repos/pjhyett/blackjax/issues/events{/number}",
        "events_url": "https://api.github.com/repos/pjhyett/blackjax/events",
        "assignees_url": "https://api.github.com/repos/pjhyett/blackjax/assignees{/user}",
        "branches_url": "https://api.github.com/repos/pjhyett/blackjax/branches{/branch}",
        "tags_url": "https://api.github.com/repos/pjhyett/blackjax/tags",
        "blobs_url": "https://api.github.com/repos/pjhyett/blackjax/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/pjhyett/blackjax/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/pjhyett/blackjax/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/pjhyett/blackjax/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/pjhyett/blackjax/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/pjhyett/blackjax/languages",
        "stargazers_url": "https://api.github.com/repos/pjhyett/blackjax/stargazers",
        "contributors_url": "https://api.github.com/repos/pjhyett/blackjax/contributors",
        "subscribers_url": "https://api.github.com/repos/pjhyett/blackjax/subscribers",
        "subscription_url": "https://api.github.com/repos/pjhyett/blackjax/subscription",
        "commits_url": "https://api.github.com/repos/pjhyett/blackjax/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/pjhyett/blackjax/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/pjhyett/blackjax/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/pjhyett/blackjax/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/pjhyett/blackjax/contents/{+path}",
        "compare_url": "https://api.github.com/repos/pjhyett/blackjax/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/pjhyett/blackjax/merges",
        "archive_url": "https://api.github.com/repos/pjhyett/blackjax/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/pjhyett/blackjax/downloads",
        "issues_url": "https://api.github.com/repos/pjhyett/blackjax/issues{/number}",
        "pulls_url": "https://api.github.com/repos/pjhyett/blackjax/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/pjhyett/blackjax/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/pjhyett/blackjax/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/pjhyett/blackjax/labels{/name}",
        "releases_url": "https://api.github.com/repos/pjhyett/blackjax/releases{/id}",
        "deployments_url": "https://api.github.com/repos/pjhyett/blackjax/deployments",
        "created_at": "2009-01-21T20:45:27Z",
        "updated_at": "2024-02-05T21:14:51Z",
        "pushed_at": "2009-01-21T20:50:19Z",
        "git_url": "git://github.com/pjhyett/blackjax.git",
        "ssh_url": "git@github.com:pjhyett/blackjax.git",
        "clone_url": "https://github.com/pjhyett/blackjax.git",
        "svn_url": "https://github.com/pjhyett/blackjax",
        "homepage": "",
        "size": 170,
        "stargazers_count": 12,
        "watchers_count": 12,
        "language": "Ruby",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 9,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 9,
        "open_issues": 0,
        "watchers": 12,
        "default_branch": "master"
    }
]